Ecommerece_Website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# from django.views.static import serve
# from django.conf.urls import url

urlpatterns = [
    path('jet/', include('jet.urls')),
    path('jet/dashboard', include('jet.dashboard.urls','jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path ,include
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('search',views.search,name='search'),
    path('category-list',views.category_list,name='category-list'),
    path('brand-list',views.brand_list,name='brand-list'),
    path('product-list',views.product_list,name='product-list'),
    path('category-product-list/<int:cat_id>',views.category_product_list,name='category-product-list'),
    path('brand-product-list/<int:brand_id>',views.brand_product_list,name='brand-product-list'),
    path('product/<str:slug>/<int:id>',views.product_detail,name='product_detail'),
    path('filter-data/',views.filter_data,name='filter_data'),
    path('load-more-data/',views.load_more_data,name='load_more_data'),
    path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    path('cart',views.cart_list,name='cart'),
    path('delete-from-cart',views.delete_cart_item,name='delete-from-cart'),
    path('update-cart',views.update_cart_item,name='update-cart'),
    path('account/signup',views.signup,name='signup'),
    path('checkout',views.checkout,name='checkout'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('save-review/<int:pid>',views.save_review, name='save-review'),
    #USer Section
    path('my-dashboard',views.my_dashboard, name='my-dashboard'),
    path('my-orders',views.my_orders, name='my_orders'),
    path('my-orders-items/<int:id>',views.my_order_items, name='my_order_items'),
    
    #Wishlist
    path('add-wishlist',views.add_wishlist, name='add_wishlist'),
    path('my-wishlist',views.my_wishlist, name='my_wishlist'),

    #My reviews
    path('my-reviews',views.my_reviews, name='my-reviews'),
    # My AddressBook
    path('my-addressbook',views.my_addressbook, name='my-addressbook'),
    path('add-address',views.save_address, name='add-address'),
    path('activate-address',views.activate_address, name='activate-address'),
    path('update-address/<int:id>',views.update_address, name='update-address'),
    path('edit-profile',views.edit_profile, name='edit-profile'),
    


    

    
]

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
# Create your models here.


# Banner
class Banner(models.Model):
    img=models.ImageField(upload_to="brand_imgs/")
    alt_text=models.CharField(max_length=300)
    def image_tag(self):
        return mark_safe(f'<img src="{self.img.url}" width="50" height="50">')    
    def __str__(self):
        return self.alt_text


# Category
class Category(models.Model):
    title =models.CharField(max_length=100)
    image=models.ImageField(upload_to="cat_imgs/")

    class Meta:
        verbose_name_plural='Categories'
   
    def image_tag(self):
       return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))    
    def __str__(self):
        return self.title

# Brand
class Brand(models.Model):
    title =models.CharField(max_length=100)
    image=models.ImageField(upload_to="brand_imgs/")
    def __str__(self):
        return self.title
    
# Color
class Color(models.Model):
    title =models.CharField(max_length=100)
    color_code=models.CharField(max_length=100)


    def color_bg(self):
        return mark_safe('<div style="height:50px; width:50px;background-color:%s "></div>' % (self.color_code))  

    def __str__(self):
        return self.title

# Size
class Size(models.Model):
    title =models.CharField(max_length=100)

    def __str__(self):
        return self.title
            
# Product
class Product(models.Model):
    title =models.CharField(max_length=200)
    image=models.ImageField(upload_to="product_imgs/")
    slug=models.CharField(max_length=400)
    detail=models.TextField()
    specs=models.TextField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    size=models.ForeignKey(Size,on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    is_featured=models.BooleanField(default=False)

    def __str__(self):
        return self.title

# ProductAttribute
class ProductAttribute(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    size=models.ForeignKey(Size,on_delete=models.CASCADE) 
    price= models.PositiveIntegerField()
    image=models.ImageField(upload_to="product_imgs/",null=True)
    
    def __str__(self):
        return self.product.title
        
    def image_tag(self):
        return mark_safe(f'<img src="{self.image.url}" width="50" height="50">')      

#Order Model
status_choice=(
    ('porcess','In process'),
    ('shipped','Shipped'),
    ('delivered','Delivered')
)
class CartOrder(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    total_amt=models.FloatField()
    paid_status= models.BooleanField(default=False)
    order_dt=models.DateTimeField(auto_now_add=True)
    order_status=models.CharField(choices=status_choice,default='process',max_length=150)

#Orders Item
class CartOrderItems(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    invoice_no=models.CharField(max_length=150)
    item=models.CharField(max_length=150)
    image=models.CharField(max_length=200)
    qty=models.IntegerField(max_length=200)
    price= models.FloatField()
    total= models.FloatField()

    class Meta:
        verbose_name_plural='CartOrderItems'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50">'% (self.image))        

#Product Review
RATING=(
    (1,'1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
)
class ProductReview(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    review_text=models.TextField()
    review_rating=models.CharField(choices=RATING,max_length=150)

    def get_review_rating(self):
        return self.review_rating

#Wishlist
class Wishlist(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)    

#Address Book
class UserAddressBook(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    mobile=models.CharField(max_length=50,null=True)
    address=models.TextField()
    status=models.BooleanField(default=False)  

main/views.py
from unicodedata import category
from urllib.request import HTTPRedirectHandler
from django.http import  JsonResponse
from django.shortcuts import render, redirect
from .models import Category , Brand , Product , Category,Banner,ProductAttribute,CartOrder,CartOrderItems,ProductReview,User, Wishlist,UserAddressBook
from django.template.loader import render_to_string
from django.db.models import Max,Min,Count,Avg
from django.db.models.functions import ExtractMonth
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from .forms import AddressBookForm, ProfileForm, SignupForm,ReviewAdd
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
# from django.contrib import messages
# Create your views here.

# Home Page
def home(request):
    banners=Banner.objects.all().order_by('-id')
    data=Product.objects.filter(is_featured=True).order_by('-id')
    return render(request,'index.html',{'data':data, 'banners':banners})

# Category
def category_list(request):
    data = Category.objects.all().order_by('-id')
    return render (request,'category_list.html',{'data':data})

# Brand List
def brand_list(request):
    data = Brand.objects.all().order_by('-id')
    return render (request,'brand_list.html',{'data':data})


# Product List
def product_list(request):
	total_data=Product.objects.count()
	data=Product.objects.all().order_by('-id')[:3]
	min_price=ProductAttribute.objects.aggregate(Min('price'))
	max_price=ProductAttribute.objects.aggregate(Max('price'))
	return render(request,'product_list.html',
		{
			'data':data,
			'total_data':total_data,
			'min_price':min_price,
			'max_price':max_price,
		}
		)


# Product List according to Category
def category_product_list(request,cat_id):
    category=Category.objects.get(id=cat_id)
    data =Product.objects.filter(category=category).order_by('-id')
    return render (request,'category_product_list.html',{
        'data':data,

    }
    )       

    # Product List according to Brands
def brand_product_list(request,brand_id):
	brand=Brand.objects.get(id=brand_id)
	data=Product.objects.filter(brand=brand).order_by('-id')
	return render(request,'category_product_list.html',{
			'data':data,
			})
#product Detail
def product_detail(request,slug,id):
	product=Product.objects.get(id=id)
	related_products=Product.objects.filter(category=product.category).exclude(id=id)[:4]
	colors= ProductAttribute.objects.filter(product=product).values('color__id', 'color__title','color__color_code',).distinct()
	sizes= ProductAttribute.objects.filter(product=product).values('size__id', 'size__title','price','color__id',).distinct()
	reviewForm=ReviewAdd()

	#Check
	canAdd=True
	reviewCheck=ProductReview.objects.filter(user=request.user,product=product).count()
	if request.user.is_authenticated:
		if reviewCheck>0:
			canAdd=False

	#End
	#Fetch reviews
	reviews=ProductReview.objects.filter(product=product)
	
	#End

	#Fetch avg rating
	avg_reviews=ProductReview.objects.filter(product=product).aggregate(avg_rating=Avg('review_rating'))
	
	#End
	return render(request, 'product_detail.html',{'data':product,'related':related_products,'colors':colors,'sizes':sizes,'form':reviewForm,'canAdd':canAdd,'reviews':reviews,'avg_reviews':avg_reviews} )

# Search
def search(request):
    q=request.GET['q']
    data=Product.objects.filter(title__icontains=q)
    return render(request, 'search.html',{'data':data} )


#Filter Data
def filter_data(request):
	colors=request.GET.getlist('color[]')
	categories=request.GET.getlist('category[]')
	brands=request.GET.getlist('brand[]')
	sizes=request.GET.getlist('size[]')
	minPrice=request.GET['minPrice']
	maxPrice=request.GET['maxPrice']
	allProducts=Product.objects.all().order_by('-id').distinct()
	allProducts=allProducts.filter(productattribute__price__gte=minPrice)
	allProducts=allProducts.filter(productattribute__price__lte=maxPrice)
	if len(colors)>0:
		allProducts=allProducts.filter(productattribute__color__id__in=colors).distinct()
	if len(categories)>0:
		allProducts=allProducts.filter(category__id__in=categories).distinct()
	if len(brands)>0:
		allProducts=allProducts.filter(brand__id__in=brands).distinct()
	if len(sizes)>0:
		allProducts=allProducts.filter(productattribute__size__id__in=sizes).distinct()
	t=render_to_string('ajax/product-list.html',{'data':allProducts})
	return JsonResponse({'data':t})



#Load more Data
def load_more_data(request):
	offset=int(request.GET['offset'])
	limit=int(request.GET['limit'])
	data=Product.objects.all().order_by('-id')[offset:offset+limit]
	t=render_to_string('ajax/product-list.html',{'data':data})
	return JsonResponse({'data':t}
        )    
def add_to_cart(request):
	# del request.session['cartdata']
	cart_p={}
	cart_p[str(request.GET['id'])]={
		'image':request.GET['image'],
		'title':request.GET['title'],
		'qty':request.GET['qty'],
		'price':request.GET['price'],
	}
	if 'cartdata' in request.session:
		if str(request.GET['id']) in request.session['cartdata']:
			cart_data=request.session['cartdata']
			cart_data[str(request.GET['id'])]['qty']=int(cart_p[str(request.GET['id'])]['qty'])
			cart_data.update(cart_data)
			request.session['cartdata']=cart_data
		else:
			cart_data=request.session['cartdata']
			cart_data.update(cart_p)
			request.session['cartdata']=cart_data
	else:
		request.session['cartdata']=cart_p
	return JsonResponse({'data':request.session['cartdata'],'totalitems':len(request.session['cartdata'])})

# Cart List Page
def cart_list(request):
	total_amt=0
	if 'cartdata' in request.session:
		for p_id,item in request.session['cartdata'].items():
			total_amt+=int(item['qty'])*float(item['price'])
		return render(request, 'cart.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
	else:
		return render(request, 'cart.html',{'cart_data':'','totalitems':0,'total_amt':total_amt})


# Delete Cart Item
def delete_cart_item(request):
	p_id=str(request.GET['id'])
	if 'cartdata' in request.session:
		if p_id in request.session['cartdata']:
			cart_data=request.session['cartdata']
			del request.session['cartdata'][p_id]
			request.session['cartdata']=cart_data
	total_amt=0
	for p_id,item in request.session['cartdata'].items():
		total_amt+=int(item['qty'])*float(item['price'])
	t=render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
	return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

# Update Cart Item
def update_cart_item(request):
	p_id=str(request.GET['id'])
	p_qty=request.GET['qty']
	if 'cartdata' in request.session:
		if p_id in request.session['cartdata']:
			cart_data=request.session['cartdata']
			cart_data[str(request.GET['id'])]['qty']=p_qty
			request.session['cartdata']=cart_data
	total_amt=0
	for p_id,item in request.session['cartdata'].items():
		total_amt+=int(item['qty'])*float(item['price'])
	t=render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
	return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

#Signup
def signup(request):
	if request.method=='POST':
		form=SignupForm(request.POST)
		print("test--",form)
		if form.is_valid():
			form.save()
			username=form.cleaned_data.get('username')
			pwd=form.cleaned_data.get('password1')
			user=authenticate(username=username,password=pwd)
			login(request, user)
			return redirect('home')
		# else:
		# 	return render(request,'registration/signup.html',{'form':form})
	else:
		form=SignupForm
	return render(request,'registration/signup.html',{'form':form})

#Checkout
@login_required
def checkout(request):
	total_amt=0
	totalAmt=0
	if 'cartdata' in request.session:
		for p_id,item in request.session['cartdata'].items():
			totalAmt+=int(item['qty'])*float(item['price'])
		# Order
		order=CartOrder.objects.create(
				user=request.user,
				total_amt=totalAmt
			)
		# End
		for p_id,item in request.session['cartdata'].items():
			total_amt+=int(item['qty'])*float(item['price'])
			# OrderItems
			items=CartOrderItems.objects.create(
				order=order,
				invoice_no='INV-'+str(order.id),
				item=item['title'],
				image=item['image'],
				qty=item['qty'],
				price=item['price'],
				total=float(item['qty'])*float(item['price'])
				)
			# End
		# Process Payment
		host = request.get_host()
		paypal_dict = {
		    'business': settings.PAYPAL_RECEIVER_EMAIL,
		    'amount': total_amt,
		    'item_name': 'OrderNo-'+str(order.id),
		    'invoice': 'INV-'+str(order.id),
		    'currency_code': 'USD',
		    'notify_url': 'http://{}{}'.format(host,reverse('paypal-ipn')),
		    'return_url': 'http://{}{}'.format(host,reverse('payment_done')),
		    'cancel_return': 'http://{}{}'.format(host,reverse('payment_cancelled')),
		}
		form = PayPalPaymentsForm(initial=paypal_dict)
		address=UserAddressBook.objects.filter(user=request.user,status=True).first()
		return render(request, 'checkout.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt,'form':form,'address':address})

@csrf_exempt
def payment_done(request):
    returnData=request.POST
    return render(request, 'payment-success.html',{'data',returnData})

@csrf_exempt
def payment_canceled(request):  
    return render(request,'payment-fail.html')

#Save review
def save_review(request,pid):
	product=Product.objects.get(pk=pid)
	user=request.user
	review=ProductReview.objects.create(
		user=user,
		product=product,
		review_text=request.POST['review_text'],
		review_rating=request.POST['review_rating'],

	)
	data={
		'user':user.username,
		'review_text':request.POST['review_text'],
		'review_rating':request.POST['review_rating'],

	}

main/templates/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Brands</h3>
	<div class="row">
		{% if data %}
			{% for brand in data %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
				<a href="/brand-product-list/{{brand.id}}"><img src="/media/{{brand.image}}" class="card-img-top" alt="{{brand.title}}" /></a>
				<div class="card-body">
					<h6 class="card-text"><a href="#">{{brand.title}}</a></h6>
				</div>
				</div>
			</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

main/templates/brand_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
				          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
				          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5 
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><a href="products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

main/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Categories</h3>
	<div class="row">
		{% if data %}
			{% for cat in data %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
				<a href="/category-product-list/{{cat.id}}"><img src="/media/{{cat.productattribute_set.first.image}}" class="card-img-top" alt="{{cat.title}}" /></a>
				<div class="card-body">
					<h6 class="card-text"><a href="#">{{cat.title}}</a></h6>
				</div>
				</div>
			</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

main/templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
				          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
				          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5 
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			{% comment %} <p class="my-4 text-center"><a href="products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p> {% endcomment %}
			<p class="my-4 text-center"><button id="loadMore" data-total="{{total_data}}" data-limit="3" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
    {% else %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
    {% endif %}
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <div class="carousel-item active">
      {% else %}
      <div class="carousel-item">
      {% endif %}
      <img src="/media/{{banner.img}}" class="d-block w-100" alt="...">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Featured Products</h3>
	<div class="row">
    {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
			    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
          <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
			  </div>
			  <div class="card-footer">
          {{product.productattribute_set.first.color.title}}
          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
			  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
      {% if user.is_authenticated %} 
			  	<button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
           {% else %} 
          <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
          {% endif %} 
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
    {% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

main/templates/payment-fail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
    <p>Payment Failed</p>
</main>
{% endblock %}

main/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1"><span class="text-muted">Search result for</span> {{request.GET.q}}</h3>
	<div class="row">
    {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h6>
			  </div>
			  <div class="card-footer">
			  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
    {% endfor %}
	</div>
</main>
{% endblock %}